import { useEffect, useMemo, useState } from 'react';
import { Pencil, Plus, Target, Trash2, X } from 'lucide-react';
import { supabase } from '@/lib/supabase';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';

const EMPTY=()=>({category:'Food',month:new Date().toISOString().slice(0,7)+'-01',monthly_limit:''});
export const route={path:'/budgets',layout:'owner',access:'authenticated'};
export const nav={label:'Budgets',to:'/budgets',icon:'Target',section:'Planning',order:3};

export default function Budgets(){
 const [data,setData]=useState([]),[loading,setLoading]=useState(true),[error,setError]=useState(''),[editing,setEditing]=useState(null),[saving,setSaving]=useState(false),[form,setForm]=useState(EMPTY());
 async function run(){setLoading(true);setError('');const {data:rows,error:e}=await supabase.from('budgets').select('*').order('month',{ascending:false});if(e)setError(e.message);else setData(rows??[]);setLoading(false)}
 useEffect(()=>{run()},[]);
 const total=useMemo(()=>data.reduce((s,r)=>s+Number(r.monthly_limit||0),0),[data]);
 async function save(e){e.preventDefault();setSaving(true);try{const {data:{user},error:userError}=await supabase.auth.getUser();if(userError||!user)throw userError||new Error('Your session has expired. Please sign in again.');const payload={user_id:user.id,name:form.category,category:form.category,month:form.month,monthly_limit:Number(form.monthly_limit)};const result=editing==='new'?await supabase.from('budgets').insert(payload):await supabase.from('budgets').update(payload).eq('id',editing);if(result.error)throw result.error;setEditing(null);setForm(EMPTY());await run()}catch(e){setError(e.message||'Could not save budget')}finally{setSaving(false)}}
 async function remove(id){if(!confirm('Delete this budget?'))return;const {error:e}=await supabase.from('budgets').delete().eq('id',id);if(e)setError(e.message);else await run()}
 return <div className="space-y-7">
  <header className="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-sm font-semibold text-success">Planning</p><h1 className="mt-1 font-heading text-4xl sm:text-5xl">Budgets</h1><p className="mt-2 text-sm text-muted-foreground">Give each important category a ceiling for the month.</p></div><Button onClick={()=>{setEditing('new');setForm(EMPTY())}}><Plus size={17}/> Add budget</Button></header>
  <div className="rounded-2xl bg-sidebar p-6 text-sidebar-foreground shadow-md"><div className="flex items-start justify-between gap-4"><div><p className="text-sm text-sidebar-foreground/70">Planned monthly spend</p><p className="mt-1 font-heading text-4xl">₹{total.toLocaleString('en-IN')}</p></div><span className="grid size-11 place-items-center rounded-xl bg-sidebar-primary text-sidebar-primary-foreground"><Target size={21}/></span></div><p className="mt-4 max-w-xl text-sm leading-6 text-sidebar-foreground/70">Budgets are guardrails, not restrictions.</p></div>
  {error&&<div className="rounded-2xl border border-destructive/30 bg-card p-5"><p className="font-semibold text-destructive">Budgets couldn't load.</p><p className="mt-1 text-sm text-muted-foreground">{error}</p><Button variant="outline" size="sm" onClick={run} className="mt-3">Retry</Button></div>}
  <section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{loading&&[1,2,3,4].map(n=><div key={n} className="h-48 animate-pulse rounded-2xl bg-muted"/>)}{!loading&&data.map(row=><article key={row.id} className="rounded-2xl border border-border bg-card p-5 shadow-xs"><div className="flex items-start justify-between"><span className="rounded-full bg-muted px-2.5 py-1 text-xs font-semibold">{row.category}</span><div className="flex"><Button variant="ghost" size="icon" onClick={()=>{setEditing(row.id);setForm({category:row.category,month:row.month,monthly_limit:String(row.monthly_limit)})}}><Pencil size={15}/></Button><Button variant="ghost" size="icon" onClick={()=>remove(row.id)} className="text-destructive"><Trash2 size={15}/></Button></div></div><p className="mt-8 font-heading text-3xl">₹{Number(row.monthly_limit).toLocaleString('en-IN')}</p><p className="mt-1 text-xs text-muted-foreground">monthly limit · {String(row.month).slice(0,7)}</p></article>)}{!loading&&!data.length&&<div className="sm:col-span-2 xl:col-span-4 rounded-2xl border border-dashed border-border bg-card p-12 text-center"><Target className="mx-auto text-primary" size={28}/><p className="mt-4 font-semibold">No budgets yet.</p><p className="mt-1 text-sm text-muted-foreground">Create your first monthly budget.</p></div>}</section>
  {editing&&<div className="fixed inset-0 z-50 grid place-items-center bg-foreground/30 p-4"><div className="w-full max-w-md rounded-2xl border border-border bg-card p-6 shadow-lg"><div className="flex items-start justify-between"><div><h2 className="font-heading text-3xl">{editing==='new'?'Add budget':'Edit budget'}</h2><p className="mt-1 text-sm text-muted-foreground">Saved privately to your account.</p></div><Button variant="ghost" size="icon" onClick={()=>setEditing(null)}><X size={18}/></Button></div><form onSubmit={save} className="mt-6 grid gap-4"><label className="grid gap-1.5 text-sm font-semibold">Category<select value={form.category} onChange={e=>setForm({...form,category:e.target.value})} className="h-10 rounded-md border border-input bg-background px-3 font-normal"><option>Food</option><option>Housing</option><option>Transport</option><option>Personal</option><option>Education</option><option>Health</option><option>Other</option></select></label><label className="grid gap-1.5 text-sm font-semibold">Month<Input type="date" value={form.month} onChange={e=>setForm({...form,month:e.target.value})}/></label><label className="grid gap-1.5 text-sm font-semibold">Monthly limit<Input required type="number" min="0" step="1" value={form.monthly_limit} onChange={e=>setForm({...form,monthly_limit:e.target.value})} placeholder="5000"/></label><div className="flex justify-end gap-2"><Button type="button" variant="ghost" onClick={()=>setEditing(null)}>Cancel</Button><Button disabled={saving} type="submit">{saving?'Saving…':'Save budget'}</Button></div></form></div></div>}
 </div>
}
