import { useEffect, useMemo, useState } from 'react';
import { Pencil, Plus, ReceiptText, Search, Trash2, X } from 'lucide-react';
import { supabase } from '@/lib/supabase';
import { formatLocalDate } from '@/utils/date';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';

const EMPTY=()=>({name:'',amount:'',type:'Expense',category:'Food',merchant:'',date:new Date().toISOString().slice(0,10),payment_method:'UPI',note:''});
export const route={path:'/transactions',layout:'owner',access:'authenticated'};
export const nav={label:'Transactions',to:'/transactions',icon:'ReceiptText',section:'Workspace',order:2};

export default function Transactions(){
 const [data,setData]=useState([]),[loading,setLoading]=useState(true),[error,setError]=useState(''),[query,setQuery]=useState(''),[type,setType]=useState('All'),[sort,setSort]=useState('date'),[editing,setEditing]=useState(null),[saving,setSaving]=useState(false),[deleting,setDeleting]=useState(null),[form,setForm]=useState(EMPTY());
 async function run(){setLoading(true);setError('');const {data:rows,error:e}=await supabase.from('transactions').select('*').order('date',{ascending:false}).limit(100);if(e)setError(e.message);else setData(rows??[]);setLoading(false);}
 useEffect(()=>{run();const open=()=>{setEditing('new');setForm(EMPTY())};window.addEventListener('ledgerly:new-transaction',open);return()=>window.removeEventListener('ledgerly:new-transaction',open)},[]);
 const rows=useMemo(()=>[...data].filter(r=>type==='All'||r.type===type).filter(r=>[r.merchant,r.category,r.name,r.note].join(' ').toLowerCase().includes(query.toLowerCase())).sort((a,b)=>sort==='amount'?Number(b.amount)-Number(a.amount):String(b.date).localeCompare(String(a.date))),[data,type,query,sort]);
 const set=(k,v)=>setForm(x=>({...x,[k]:v}));
 async function save(e){e.preventDefault();if(!form.merchant.trim()||!form.amount||!form.date)return;setSaving(true);try{const payload={...form,name:form.name.trim()||form.merchant.trim(),amount:Number(form.amount)};const result=editing==='new'?await supabase.from('transactions').insert(payload):await supabase.from('transactions').update(payload).eq('id',editing);if(result.error)throw result.error;setEditing(null);setForm(EMPTY());await run()}catch(e){setError(e.message||'Could not save transaction.')}finally{setSaving(false)}}
 async function remove(id){if(!confirm('Delete this transaction? This cannot be undone.'))return;setDeleting(id);const {error:e}=await supabase.from('transactions').delete().eq('id',id);if(e)setError(e.message);else await run();setDeleting(null)}
 return <div className="space-y-7">
  <header className="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-sm font-semibold text-success">Ledger</p><h1 className="mt-1 font-heading text-4xl sm:text-5xl">Transactions</h1><p className="mt-2 text-sm text-muted-foreground">Every rupee in one searchable, editable place.</p></div><Button onClick={()=>{setEditing('new');setForm(EMPTY())}}><Plus size={17}/> Add transaction</Button></header>
  <section className="rounded-2xl border border-border bg-card p-4 shadow-xs"><div className="grid gap-3 md:grid-cols-[1fr_160px_160px]"><div className="relative"><Search className="absolute left-3 top-1/2 -translate-y-1/2 text-muted-foreground" size={17}/><Input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search merchant, category, notes..." className="pl-9"/></div><select value={type} onChange={e=>setType(e.target.value)} className="h-10 rounded-md border border-input bg-background px-3 text-sm"><option>All</option><option>Expense</option><option>Income</option></select><select value={sort} onChange={e=>setSort(e.target.value)} className="h-10 rounded-md border border-input bg-background px-3 text-sm"><option value="date">Newest first</option><option value="amount">Largest first</option></select></div></section>
  {error&&<div className="rounded-2xl border border-destructive/30 bg-card p-5"><p className="font-semibold text-destructive">Something went wrong.</p><p className="mt-1 text-sm text-muted-foreground">{error}</p><Button variant="outline" size="sm" onClick={run} className="mt-3">Retry</Button></div>}
  <section className="overflow-hidden rounded-2xl border border-border bg-card shadow-xs"><div className="hidden grid-cols-[1.3fr_1fr_.8fr_.8fr_110px] gap-4 border-b border-border bg-muted px-5 py-3 text-[11px] font-bold uppercase tracking-[0.12em] text-muted-foreground md:grid"><span>Transaction</span><span>Category</span><span>Date</span><span>Amount</span><span/></div>{loading&&[1,2,3,4].map(n=><div key={n} className="h-20 border-b border-border animate-pulse bg-muted/30"/>)}{!loading&&rows.map(row=><div key={row.id} className="grid gap-3 border-b border-border px-5 py-4 last:border-b-0 md:grid-cols-[1.3fr_1fr_.8fr_.8fr_110px] md:items-center"><div><p className="font-semibold">{row.merchant}</p><p className="text-xs text-muted-foreground">{row.payment_method} · {row.note||row.name}</p></div><span className="w-fit rounded-full bg-muted px-2.5 py-1 text-xs font-semibold">{row.category}</span><span className="text-sm text-muted-foreground">{formatLocalDate(row.date)}</span><span className={row.type==='Income'?'font-semibold text-success':'font-semibold'}>{row.type==='Income'?'+':'-'}₹{Number(row.amount).toLocaleString('en-IN')}</span><div className="flex gap-1 md:justify-end"><Button variant="ghost" size="icon" onClick={()=>{setEditing(row.id);setForm({...row,amount:String(row.amount)})}}><Pencil size={16}/></Button><Button variant="ghost" size="icon" disabled={deleting===row.id} onClick={()=>remove(row.id)} className="text-destructive"><Trash2 size={16}/></Button></div></div>)}{!loading&&rows.length===0&&<div className="py-16 text-center"><ReceiptText className="mx-auto text-primary" size={28}/><p className="mt-4 font-semibold">No transactions yet.</p><p className="mt-1 text-sm text-muted-foreground">Add your first transaction to get started.</p></div>}</section>
  {editing&&<div className="fixed inset-0 z-50 grid place-items-center bg-foreground/30 p-4"><div className="w-full max-w-xl rounded-2xl border border-border bg-card p-6 shadow-lg"><div className="flex items-start justify-between"><div><h2 className="font-heading text-3xl">{editing==='new'?'Add transaction':'Edit transaction'}</h2><p className="mt-1 text-sm text-muted-foreground">Saved privately to your account.</p></div><Button variant="ghost" size="icon" onClick={()=>setEditing(null)}><X size={18}/></Button></div><form onSubmit={save} className="mt-6 grid gap-4 sm:grid-cols-2"><label className="grid gap-1.5 text-sm font-semibold">Type<select value={form.type} onChange={e=>set('type',e.target.value)} className="h-10 rounded-md border border-input bg-background px-3 font-normal"><option>Expense</option><option>Income</option></select></label><label className="grid gap-1.5 text-sm font-semibold">Amount<Input required type="number" min="0" step="0.01" value={form.amount} onChange={e=>set('amount',e.target.value)}/></label><label className="grid gap-1.5 text-sm font-semibold">Merchant<Input required value={form.merchant} onChange={e=>set('merchant',e.target.value)} placeholder="e.g. Campus Cafe"/></label><label className="grid gap-1.5 text-sm font-semibold">Category<select value={form.category} onChange={e=>set('category',e.target.value)} className="h-10 rounded-md border border-input bg-background px-3 font-normal"><option>Food</option><option>Housing</option><option>Transport</option><option>Work</option><option>Personal</option><option>Education</option><option>Health</option><option>Other</option></select></label><label className="grid gap-1.5 text-sm font-semibold">Date<Input required type="date" value={form.date} onChange={e=>set('date',e.target.value)}/></label><label className="grid gap-1.5 text-sm font-semibold">Payment method<select value={form.payment_method} onChange={e=>set('payment_method',e.target.value)} className="h-10 rounded-md border border-input bg-background px-3 font-normal"><option>UPI</option><option>Card</option><option>Cash</option><option>Bank Transfer</option><option>Other</option></select></label><label className="grid gap-1.5 text-sm font-semibold sm:col-span-2">Note<Input value={form.note} onChange={e=>set('note',e.target.value)} placeholder="Optional context"/></label><div className="flex justify-end gap-2 sm:col-span-2"><Button type="button" variant="ghost" onClick={()=>setEditing(null)}>Cancel</Button><Button disabled={saving} type="submit">{saving?'Saving…':'Save transaction'}</Button></div></form></div></div>}
 </div>
}
